import * as fs from 'fs';
import * as path from 'path';
import { runtimeStore, Artifact } from './runtime_loop';

export interface SiteGeneratorResult {
  outputDir: string;
  files: string[];
  error?: string;
}

function findArtifactsByType(type: string): Artifact[] {
  return runtimeStore.artifacts.filter((a) => a.type === type);
}

function htmlTemplate(title: string, nav: string[], body: string): string {
  const navLinks = nav
    .map((p) => {
      const href = p === 'home' ? 'index.html' : `${p}.html`;
      return `<a href="${href}">${p.charAt(0).toUpperCase() + p.slice(1)}</a>`;
    })
    .join(' | ');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8fafc; color: #1e293b; line-height: 1.6; }
    nav { background: #0f172a; color: #e2e8f0; padding: 16px 32px; font-size: 14px; }
    nav a { color: #93c5fd; text-decoration: none; margin-right: 8px; }
    nav a:hover { text-decoration: underline; }
    .hero { background: #1e40af; color: white; padding: 64px 32px; text-align: center; }
    .hero h1 { font-size: 2rem; margin-bottom: 12px; }
    .hero p { font-size: 1.1rem; opacity: 0.9; max-width: 600px; margin: 0 auto; }
    .cta { display: inline-block; margin-top: 24px; background: #f59e0b; color: #1e293b; padding: 12px 32px; border-radius: 6px; font-weight: 700; text-decoration: none; }
    main { max-width: 800px; margin: 32px auto; padding: 0 24px; }
    section { background: white; border-radius: 8px; padding: 32px; margin-bottom: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.06); }
    section h2 { margin-bottom: 12px; color: #1e40af; }
    footer { background: #0f172a; color: #94a3b8; padding: 24px 32px; text-align: center; font-size: 13px; margin-top: 48px; }
    .badge { display: inline-block; background: #dbeafe; color: #1e40af; padding: 2px 10px; border-radius: 4px; font-size: 12px; margin: 4px 2px; }
  </style>
</head>
<body>
  <nav>${navLinks}</nav>
  ${body}
  <footer>Generated by GhostClaw Runtime &mdash; ${new Date().toISOString()}</footer>
</body>
</html>`;
}

function buildHomePage(pageContent: any, siteStructure: any): string {
  const pc = pageContent?.home || {};
  const cta = pc.cta ? `<a class="cta" href="contact.html">${pc.cta}</a>` : '';
  const sections = (pc.sections || [])
    .map((s: string) => `<span class="badge">${s}</span>`)
    .join(' ');

  const body = `<div class="hero">
  <h1>${pc.title || siteStructure?.businessName || 'Welcome'}</h1>
  <p>${pc.hero || ''}</p>
  ${cta}
</div>
<main>
  <section>
    <h2>What We Offer</h2>
    <p>${sections || 'Professional services tailored to your needs.'}</p>
  </section>
</main>`;

  const pages = siteStructure?.pages || ['home', 'services', 'contact'];
  return htmlTemplate(pc.title || 'Home', pages, body);
}

function buildServicesPage(pageContent: any, siteStructure: any): string {
  const pc = pageContent?.services || {};
  const sections = (pc.sections || [])
    .map((s: string) => `<section><h2>${s.replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase())}</h2><p>Details coming soon.</p></section>`)
    .join('\n');

  const body = `<div class="hero">
  <h1>${pc.title || 'Our Services'}</h1>
  <p>${pc.description || ''}</p>
</div>
<main>
  ${sections || '<section><h2>Services</h2><p>Full-service solutions for your project.</p></section>'}
</main>`;

  const pages = siteStructure?.pages || ['home', 'services', 'contact'];
  return htmlTemplate(pc.title || 'Services', pages, body);
}

function buildContactPage(pageContent: any, siteStructure: any): string {
  const pc = pageContent?.contact || {};

  const body = `<div class="hero">
  <h1>${pc.title || 'Contact Us'}</h1>
  <p>${pc.description || 'Get in touch with our team.'}</p>
</div>
<main>
  <section>
    <h2>Send Us a Message</h2>
    <p>Call us or fill out the form below to get started on your project.</p>
  </section>
</main>`;

  const pages = siteStructure?.pages || ['home', 'services', 'contact'];
  return htmlTemplate(pc.title || 'Contact', pages, body);
}

export function generateSite(publishEventId: string, artifactId: string): SiteGeneratorResult {
  // Find the referenced artifact
  const artifact = runtimeStore.artifacts.find((a) => a.id === artifactId);

  // Gather all pageContent and siteStructure artifacts
  const pageContentArtifacts = findArtifactsByType('generate_page_content');
  const siteStructureArtifacts = findArtifactsByType('design_site_structure');

  let pageContent: any = null;
  let siteStructure: any = null;

  // Try to get data from the specific artifact first
  if (artifact) {
    try {
      const parsed = JSON.parse(artifact.content);
      if (parsed.pageContent) pageContent = parsed.pageContent;
      if (parsed.siteStructure) siteStructure = parsed.siteStructure;
    } catch (_) { /* ignore */ }
  }

  // Fall back to any available artifacts of the right type
  if (!pageContent && pageContentArtifacts.length > 0) {
    try {
      const parsed = JSON.parse(pageContentArtifacts[pageContentArtifacts.length - 1].content);
      if (parsed.pageContent) pageContent = parsed.pageContent;
      if (!siteStructure && parsed.siteStructure) siteStructure = parsed.siteStructure;
    } catch (_) { /* ignore */ }
  }
  if (!siteStructure && siteStructureArtifacts.length > 0) {
    try {
      const parsed = JSON.parse(siteStructureArtifacts[siteStructureArtifacts.length - 1].content);
      if (parsed.siteStructure) siteStructure = parsed.siteStructure;
    } catch (_) { /* ignore */ }
  }

  if (!pageContent && !siteStructure) {
    return { outputDir: '', files: [], error: 'No pageContent or siteStructure artifacts found.' };
  }

  const outputDir = path.resolve(__dirname, '..', '..', '..', 'apps', 'api', 'output', 'sites', publishEventId);
  fs.mkdirSync(outputDir, { recursive: true });

  const files: string[] = [];

  const homeHtml = buildHomePage(pageContent, siteStructure);
  fs.writeFileSync(path.join(outputDir, 'index.html'), homeHtml);
  files.push('index.html');

  const servicesHtml = buildServicesPage(pageContent, siteStructure);
  fs.writeFileSync(path.join(outputDir, 'services.html'), servicesHtml);
  files.push('services.html');

  const contactHtml = buildContactPage(pageContent, siteStructure);
  fs.writeFileSync(path.join(outputDir, 'contact.html'), contactHtml);
  files.push('contact.html');

  return { outputDir, files };
}
